### PR TITLE
Lpstream

### PR DESCRIPTION
**Pull request by ronag**

### CODE REVIEW

**Comment by juliangruber** [comment]
What about filing this PR against the length-prefixed-stream repo instead? 🤔

**Comment by juliangruber** [comment]
Otherwise I think we could move this to a separate repo, as we wouldn't want to maintain its implementation (with tests and all, which would currently be missing) inside this project

**Comment by ronag** [comment]
> What about filing this PR against the length-prefixed-stream repo instead? 🤔

None of those projects want to move towards modern stream as far as I know. All of them are waiting for readable-stream to be updated.

**Comment by ronag** [comment]
> Otherwise I think we could move this to a separate repo, as we wouldn't want to maintain its implementation (with tests and all, which would currently be missing) inside this project

That sounds like just making things difficult. It's not soo much code nor that complex implementation. IMHO.

**Comment by juliangruber** [comment]
> That sounds like just making things difficult. It's not soo much code nor that complex implementation. IMHO.

It's making it more difficult in this moment but very much less difficult in the long run.

**Comment by vweevers** [comment]
I'm with @juliangruber, this doesn't belong here. And I'm not willing to maintain it here - without its own tests, isolated benchmarks, keeping track of upstream fixes, etc.

**Comment by ronag** [comment]
I understand. Unfortunate.

**Pull request closed without merging**
